version: '3.8'

services:
  visa-payment-service-go:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=payment.db
    volumes:
      - ./data:/root/data
    networks:
      - visa-network

networks:
  visa-network:
    driver: bridge
